# Generated by Django 5.2.7 on 2025-11-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight_number',
            new_name='flight_code',
        ),
        migrations.AddField(
            model_name='flight',
            name='punctuality',
            field=models.FloatField(default=100, help_text='Puntualidad promedio en %'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('On Time', 'On Time'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='On Time', max_length=20),
        ),
    ]
