# Generated by Django 5.2.7 on 2025-11-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_flight_number_flight_flight_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='punctuality',
            field=models.FloatField(blank=True, help_text='Puntualidad promedio en %', null=True),
        ),
    ]
